### ISSUE TITLE
Bug img bbCode

### ISSUE THREAD

**Issue by Rayzen-dev** [pvessel/bbcode-twig-extension#2]
The img bbCode translator doesn't work me... This lines do the trick for me:

`private $searchRegex  = array('/(\[url=)([^\]]+)(\])/', '/(\[url\])([^\]]+)(\])/', '`\[img\](.+)\[/img\]`' );
 private $replaceRegex = array('<a href="\2">', '<a href="\2">\2', '<img src="$1" alt="" />' );
`

**Comment by thunderer** [comment]
@pvessel you may be interested in using my shortcode library which will happily do the hard work for you: https://github.com/thunderer/Shortcode.
